# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: Build
  timeoutInMinutes: 20
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    imageName: 'shamrock:$(build.buildId)'  
  steps:

  - task: Maven@3
    displayName: 'Maven Build'
    inputs:
      goals: 'verify'
      options: '--settings azure-mvn-settings.xml -Pprotean -Dnative-image.docker-build -Pnative -Dnative-image.xmx=4g'

